# Generated by Django 6.0.4 on 2026-05-05 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_marque', models.CharField(max_length=100)),
                ('pays_origine', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('conservateur', 'Conservateur'), ('mecanicien', 'Mécanicien')], default='mecanicien', max_length=20)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=150)),
                ('annee', models.IntegerField()),
                ('chassis', models.CharField(max_length=17, unique=True)),
                ('statut', models.CharField(choices=[('en_restauration', 'En restauration'), ('restaure', 'Restauré'), ('en_attente', 'En attente'), ('a_vendre', 'À vendre')], default='en_attente', max_length=50)),
                ('cylindres', models.IntegerField()),
                ('cylindree', models.IntegerField()),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='cars.marque')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='cars.vehicule')),
            ],
        ),
    ]
